[package]
name = "defaults-watch"
version = "0.1.0"
authors = ["Tom Forbes <tom@tomforb.es>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
plist = { version="0.5.1", default_features=false}
rayon = "1.2.1"
